<a href="https://colab.research.google.com/github/gocleanwater/AI-class/blob/main/week3/iris_lib_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import pandas as pd
import numpy as np

from sklearn import datasets
data = datasets.load_iris()

# Dictionary 데이터 타입은 앞의 Pandas의 DataFrame랑 뭐가 다른데?
- print(data)를 하면 다음과 같은 결과가 나온다.<br>
```
{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
      ...
        [5.9, 3. , 5.1, 1.8]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
      ...
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
      ...
  ```
  - 우리에게 친근한 테이블 형식이 아니라 JSON 타입처럼 Key:Value 형태이다.

In [10]:
# 이를 Pandas의 DataFrame 객체로 만들어주면 다음과 같다.
df = pd.DataFrame(data.data, columns=data.feature_names) # data.data가 150×4이고, data.feature_names는 4개라 딱 들어맞아 DataFrame으로 만들 수 있다.
df['target'] = data.target # target은 여기서 따로 떨어져 있는 데이터라, 붙여줬다.
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2


# 위의 DataFrame으로 보고 알 수 있는 점
- data.data는 **다른 입력값(X)** 이다.
- data.target이 Classification에 중요한 **label(y)** 이다!!
##### **즉, 우리는 전처럼 굳이<br>y = df['target']<br>X = df.drop('target',axis=1)<br>할 필요가 없다. (이미 나눠져 있으니까!!)**

In [11]:
X = data.data
y = data.target
values, counts = np.unique(y, return_counts=True)
# y.value_counts()와 같은 행동이다. data.data와 data.target이 numpy 배열이기 때문에 pandas에서 되는 y.value_counts()가 안된다...

print(values)
print(counts)

[0 1 2]
[50 50 50]


In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)
print(X_train.shape) # 112행
print(X_test.shape) # 38행

(112, 4)
(38, 4)


In [13]:
# Logistic Regression 방식
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

clf_lr = LogisticRegression(random_state=0)
# 모델을 하나 만듦(아직 학습 전)
clf_lr.fit(X_train, y_train)
#모델을 학습

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))


--- Logistic Regression Classifier ---
0.9736842105263158
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


In [14]:
# Decision Tree 방식
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print("\n--- Decision Tree Classifier ---")
print(accuracy_score(y_test, pred_dt))
print(confusion_matrix(y_test, pred_dt))


--- Decision Tree Classifier ---
0.9736842105263158
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


In [15]:
# Random Forest 방식
from sklearn.ensemble import RandomForestClassifier # 여기 부분이 다르다!!
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

clf_rf = RandomForestClassifier(random_state=0)
clf_rf.fit(X_train, y_train)

pred_rf = clf_rf.predict(X_test)

print("\n--- Random Forest Classifier ---")
print(accuracy_score(y_test, pred_rf))
print(confusion_matrix(y_test, pred_rf))


--- Random Forest Classifier ---
0.9736842105263158
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


In [16]:
# kNN(k-Nearest Neighbor) 방식
from sklearn.neighbors import KNeighborsClassifier # 여기 부분이 다르다!!
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

knn = KNeighborsClassifier(n_neighbors=6) # 가까운 이웃(데이터) 6개를 봐라!
knn.fit(X_train, y_train)

pred_knn = knn.predict(X_test)

print("\n--- k-Nearest Neighbor Classifier ---")
print(accuracy_score(y_test, pred_knn))
print(confusion_matrix(y_test, pred_knn))




--- k-Nearest Neighbor Classifier ---
0.9736842105263158
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
